name: Checkin
on:
  schedule:
    - cron: "45 02 * * *"
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-24.04  
    name: auto checkin for traffic
    steps: 
      - name: Checkout
        uses: actions/checkout@v4  
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true
      - name: Checkin
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
      - run: ls -lart .github/actions/checkin/
      - run: chmod +x $GITHUB_WORKSPACE/.github/actions/checkin/universal.py
      - run: python $GITHUB_WORKSPACE/.github/actions/checkin/universal.py
      - name: Timestamp
        run: /bin/date
