name: Collect
on:
  # 每周日00:00执行一次
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  # 时区
  TZ: Asia/Shanghai

  # GitHub访问令牌
  GIST_PAT: ${{ secrets.GIST_PAT }}

  # GitHub用户名和Gist ID，用'/'分隔
  GIST_LINK: ${{ secrets.GIST_LINK }}

  # 您自己维护的机场列表的URL
  # 每行包括域名、优惠券和邀请码，域名必须包括，后两项可选
  CUSTOMIZE_LINK: ${{ secrets.CUSTOMIZE_LINK }}

  # 包含特殊协议，如vless、hysteria2和hysteria
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Check
        run: |
          if [ -z "$GIST_PAT" ]; then
              echo "Error: environment 'GIST_PAT' cannot be empty"
              exit 1
          fi

          if [ -z "$GIST_LINK" ]; then
              echo "Error: environment 'GIST_LINK' cannot be empty"
              exit 1
          fi

          # 使用正则表达式验证GIST_LINK格式
          if! [[ "$GIST_LINK" =~ ^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
              exit 1
          fi

      - name: Collect
        run: python -u subscribe/collect.py --all --overwrite --skip

      - name: Timestamp
        run: date
